<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.Testing" Version="10.10.0" />
    <PackageVersion Include="OpenIddict.Server.AspNetCore" Version="7.7.1" />
    <PackageVersion Include="OpenIddict.Validation.AspNetCore" Version="7.7.1" />
    <PackageVersion Include="OpenIddict.Validation.ServerIntegration" Version="7.7.1" />
    <PackageVersion Include="System.DirectoryServices.AccountManagement" Version="10.0.12" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>